openapi: 3.1.0

info:
   description: Test application to create and manage products, customers and their orders
   version: 1.0.0
   title: Clean Arch API
servers:
   - url: http://localhost:3000
     description: DEV environment
tags:
   - name: customer
     description: Operations about customers
   - name: product
     description: Operations about products
   - name: checkout
     description: Operations about orders
schemes:
   - http
paths:
   /customer/create:
      post:
         tags:
            - customer
         summary: Create a customer
         description:
         operationId: createCustomer
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: '#/components/schemas/CustomerCreateDTO'
                  examples:
                     customer:
                        value:
                           name: Charlotte Linlin
                           address:
                              street: 140 Sugar Avenue
                              number: 40
                              city: Chocolatown
                              state: Whole Cake
                              country: Totto Land
                              postalCode: 12345678
         responses:
            201:
               description: Created
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Customer'
            404:
               description: Customer not found
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
            400:
               description: Business rules validation
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseErrorValidation'
            500:
               description: Internal server error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
   /customer/find/{id}:
      get:
         tags:
            - customer
         summary: Find a customer
         operationId: findCustomer
         parameters:
            - name: id
              in: path
              schema:
                 type: string
              required: true
         responses:
            200:
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Customer'
            404:
               description: Customer not found
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
   /customer/update/{id}:
      patch:
         tags:
            - customer
         summary: Update a customer
         operationId: updateCustomer
         parameters:
            - name: id
              in: path
              schema:
                 type: string
              required: true
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: '#/components/schemas/CustomerUpdateDTO'
                  examples:
                     customer:
                        value:
                           name: Big Mom
         responses:
            200:
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Customer'
            404:
               description: Customer not found
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
            400:
               description: Business rules validation
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseErrorValidation'
            500:
               description: Internal server error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
   /customer/update-address/{id}:
      put:
         tags:
            - customer
         summary: Update a customer address
         operationId: updateAddress
         parameters:
            - name: id
              in: path
              schema:
                 type: string
              required: true
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: '#/components/schemas/AddressUpdateDTO'
                  examples:
                     customer:
                        value:
                           address:
                              street: 140 Sugar Avenue - Updated
                              number: 82
                              city: Chocolatown - Updated
                              state: Whole Cake - Updated
                              country: Totto Land - Updated
                              postalCode: 87654321
         responses:
            200:
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Customer'
            404:
               description: Customer not found
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
            400:
               description: Business rules validation
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseErrorValidation'
            500:
               description: Internal server error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
   /customer:
      get:
         tags:
            - customer
         summary: Customer listing
         operationId: listCustomer
         responses:
            200:
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/CustomerList'
   /product/create:
      post:
         tags:
            - product
         summary: Create a product
         description:
         operationId: createProduct
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: '#/components/schemas/ProductCreateDTO'
                  examples:
                     product:
                        value:
                           name: Product One
                           price: 247.9
         responses:
            201:
               description: Created
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Product'
            404:
               description: Product not found
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
            400:
               description: Business rules validation
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseErrorValidation'
            500:
               description: Internal server error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
   /product/find/{id}:
      get:
         tags:
            - product
         summary: Find a product
         operationId: findProduct
         parameters:
            - name: id
              in: path
              schema:
                 type: string
              required: true
         responses:
            200:
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Product'
            404:
               description: Customer not found
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
   /product/update/{id}:
      put:
         tags:
            - product
         summary: Update a product
         operationId: updateProduct
         parameters:
            - name: id
              in: path
              schema:
                 type: string
              required: true
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: '#/components/schemas/ProductUpdateDTO'
                  examples:
                     product:
                        value:
                           name: Product XPTO
                           price: 289.9
         responses:
            200:
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Product'
            404:
               description: Customer not found
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
            400:
               description: Business rules validation
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseErrorValidation'
            500:
               description: Internal server error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
   /product:
      get:
         tags:
            - product
         summary: Product listing
         operationId: listProduct
         responses:
            200:
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ProductList'
   /checkout/create:
      post:
         tags:
            - checkout
         summary: Create an order
         description:
         operationId: createOrder
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: '#/components/schemas/OrderCreateDTO'
                  examples:
                     product:
                        value:
                           customerId: customer-uuid
                           products:
                              - id: product-uuid
                                name: Product One
                                quantity: 2
                                price: 247.9
         responses:
            201:
               description: Created
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Order'
            404:
               description: Product not found
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
            400:
               description: Business rules validation
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseErrorValidation'
            500:
               description: Internal server error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
   /checkout/find/{id}:
      get:
         tags:
            - checkout
         summary: Find an order
         operationId: findOrder
         parameters:
            - name: id
              in: path
              schema:
                 type: string
              required: true
         responses:
            200:
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Order'
            404:
               description: Order not found
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
   /checkout/update/{id}:
      put:
         tags:
            - checkout
         summary: Update an order
         operationId: updateOrder
         parameters:
            - name: id
              in: path
              schema:
                 type: string
              required: true
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: '#/components/schemas/OrderUpdateDTO'
                  examples:
                     product:
                        value:
                           customerId: customer-uuid
                           items:
                              - id: orderItem-uuid
                                productId: product-uuid
                                productName: Product XPTO
                                quantity: 10
                                price: 289.9
         responses:
            200:
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Order'
            404:
               description: Order not found
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
            400:
               description: Business rules validation
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseErrorValidation'
            500:
               description: Internal server error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ResponseError'
   /checkout:
      get:
         tags:
            - checkout
         summary: Order listing
         operationId: listOrder
         responses:
            200:
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/OrderList'
components:
   schemas:
      Customer:
         type: object
         properties:
            id:
               type: string
            name:
               type: string
            active:
               type: boolean
            rewardPoints:
               type: number
            address:
               type: object
               properties:
                  street:
                     type: string
                  number:
                     type: number
                  city:
                     type: string
                  state:
                     type: string
                  country:
                     type: string
                  postalCode:
                     type: number
      CustomerCreateDTO:
         type: object
         properties:
            name:
               type: string
            address:
               type: object
               properties:
                  street:
                     type: string
                  number:
                     type: number
                  city:
                     type: string
                  state:
                     type: string
                  country:
                     type: string
                  postalCode:
                     type: number
      CustomerUpdateDTO:
         type: object
         properties:
            name:
               type: string
      AddressUpdateDTO:
         type: object
         properties:
            address:
               type: object
               properties:
                  street:
                     type: string
                  number:
                     type: number
                  city:
                     type: string
                  state:
                     type: string
                  country:
                     type: string
                  postalCode:
                     type: number
      CustomerList:
         type: object
         properties:
            customers:
               type: array
               $ref: '#/components/schemas/Customer'
      Product:
         type: object
         properties:
            id:
               type: string
            name:
               type: string
            price:
               type: number
      ProductCreateDTO:
         type: object
         properties:
            name:
               type: string
            price:
               type: number
      ProductUpdateDTO:
         type: object
         properties:
            name:
               type: string
            price:
               type: number
      ProductList:
         type: object
         properties:
            products:
               type: array
               $ref: '#/components/schemas/Product'
      Order:
         type: object
         properties:
            id:
               type: string
            customerId:
               type: string
            items:
               $ref: '#/components/schemas/OrderItem'
      OrderItem:
         type: object
         properties:
            id:
               type: string
            productId:
               type: string
            productName:
               type: string
            quantity:
               type: number
            price:
               type: number
      OrderCreateDTO:
         type: object
         properties:
            customerId:
               type: string
            products:
               type: array
               properties:
                  id:
                     type: string
                  name:
                     type: string
                  quantity:
                     type: number
                  price:
                     type: number
      OrderUpdateDTO:
         type: object
         properties:
            customerId:
               type: string
            items:
               type: array
               properties:
                  id:
                     type: string
                  productId:
                     type: string
                  productName:
                     type: string
                  quantity:
                     type: number
                  price:
                     type: number
      OrderList:
         type: object
         properties:
            orders:
               type: array
               $ref: '#/components/schemas/Order'
      ResponseError:
         type: object
         properties:
            status:
               type: string
            message:
               type: string
      ResponseErrorValidation:
         type: object
         properties:
            errors:
               type: array
               $ref: '#/components/schemas/ValidationError'
      ValidationError:
         type: object
         properties:
            context:
               type: string
            message:
               type: string
